name: Create predicting API with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'deploy')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t opaciorkowski/lab4:latest .

      - name: Push Docker image to Docker Hub
        run: docker push opaciorkowski/lab4:latest

      - name: Run Docker container for testing
        run: docker run -d -p 5000:5000 --name lab4 opaciorkowski/lab4:latest

      - name: Wait for 5 seconds to ensure the server starts
        run: sleep 5

      - name: Send prediction request with curl
        run: |
          curl -X POST http://127.0.0.1:5000/predict \
               -H "Content-Type: application/json" \
               -d "[\"male\", \"other\", \"yes\", \"no\", \"yes\", \"yes\", 6.2, 8.09, 0.2, 0.88915, 12, \"high\", \"other\"]"

      - name: Wait for 10 seconds
        run: sleep 10

      - name: Stop Docker container
        run: docker stop lab4
