# .github/workflows/ci.yml

name: Create predicting API with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'deploy') # Run only if 'deploy' is in the commit message

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t opaciorkowski/lab4:latest .

      - name: Push Docker image to Docker Hub
        run: docker push opaciorkowski/lab4:latest

      - name: Run Docker container for testing
        run: docker run opaciorkowski/lab4:latest

      - name: Wait for 1.5 minutes (90 seconds)
        run: sleep 90

      - name: Stop Docker container
        run: docker stop lab4